### ISSUE TITLE
right input_shape ?

### ISSUE THREAD

**Issue by hiba555** [IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization#1]
good morning 
my input_shape=(1,240,240,155)  (BRATS2018 (240*240*155) i got the following error : ValueError: Operands could not be broadcast together with shapes (128, 60, 60, 40) (128, 60, 60, 39)
(whats is the right input_shape ) ? 
Thank you

**Comment by IAmSuyogJadhav** [comment]
Hello @hiba555 , 
The input shape needs to be (c, H, W, D), where all of H, W, D are divisible by 16.

**Comment by hiba555** [comment]
Hi m'y input mri shape is  (240,240,155) from brtas2018

Le sam. 4 mai 2019 à 1:53 PM, Suyog Jadhav <notifications@github.com> a
écrit :

**Comment by IAmSuyogJadhav** [comment]
You see, 155 is not divisible by 16. Crop or resize the MRI image suitably to make it divisible by 16. It should work after that.

**Comment by hiba555** [comment]
Thanks i Will try to crop my data and test, can you send to me the training
and the predection notebooks please

Le sam. 4 mai 2019 à 2:13 PM, Suyog Jadhav <notifications@github.com> a
écrit :

**Comment by IAmSuyogJadhav** [comment]
I haven't yet used the model in a project. I will upload example training and testing notebooks once I do that.

**Comment by hiba555** [comment]
Good morning Suyog, I am a Ph.D. student from Tunisia (in the 3 years)  in
the medical imaging field based deep-learning based methods, and I am
looking for a stage in your laboratory, it is possible to send me an
invitation . thank you

Le sam. 4 mai 2019 à 5:31 PM, Suyog Jadhav <notifications@github.com> a
écrit :

**Comment by IAmSuyogJadhav** [comment]
Hello and good morning,
I am an undergraduate student and do not have a lab of my own. I was in
travel yesterday, so couldn't reply back.
Regards,
Suyog

**Comment by hiba555** [comment]
Good morning SUyog i Wang to segment brtas2018 dataset do you could help me
with à tuto on how to segment medical images or send to me an other working
code in fact i testé thé unet 3d but i have error when training of shapes
in the dice metrics that incant fix it, i Will be so happy if you could
help, it is a project that i must fineshed soon.. Thank you

**Comment by joe1chief** [comment]
> good morning
> my input_shape=(1,240,240,155) (BRATS2018 (240_240_155) i got the following error : ValueError: Operands could not be broadcast together with shapes (128, 60, 60, 40) (128, 60, 60, 39)
> (whats is the right input_shape ) ?
> Thank you

Did you use this code for single modality segmentation successfully?

**Comment by hiba555** [comment]
Hi dear no not yet I am trying , the example that you put it is not clear
xould you put a clear and colplete juputer nootbook thanks
