### ISSUE TITLE
How much GPU memory does the model need? 

### ISSUE THREAD

**Issue by ljw-struggle** [IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization#11]
I don't have Tesla V-100. Can i run it with two GTX 1080 ti?

**Comment by yf0726** [comment]
Hello,

I am afraid not. I tried a very small patch size (64,80,96, batch size=1) and had oom error. 

But on 2080ti every thing goes on well (but still I need to crop the image into patch size=96, 112, 80), and finally I got 0.86 dice score on BraTS2018 and 0.87 on another dataset.

**Comment by ljw-struggle** [comment]
> Hello,
> 
> I am afraid not. I tried a very small patch size (64,80,96, batch size=1) and had oom error.
> 
> But on 2080ti every thing goes on well (but still I need to crop the image into patch size=96, 112, 80), and finally I got 0.86 dice score on BraTS2018 and 0.87 on another dataset.

Thank you, your answer is helpful.
