### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by asifehmad** [IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization#16]
Thank you so much, sir, for the repository. Sir, I am applying the code on BraTS'19 data set. I have the access for the data set. All thing went well but at the cell number 10 i got an error: `ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-11-5506a87447e1> in <module>()
      3 # Parameters for the progress bar
      4 total = len(data_paths[:4])
----> 5 step = 25 / total
      6 
      7 for i, imgs in enumerate(data_paths[:4]):

ZeroDivisionError: division by zero`

Any help in this regard would be very appreciated. Thanks!

**Comment by IAmSuyogJadhav** [comment]
Try printing out the variable `data_paths`. Most probably the directory specified is incorrect.

**Comment by asifehmad** [comment]
> Try printing out the variable `data_paths`. Most probably the directory specified is incorrect.

Sir, didn't get it. Please, need your more help. Could you please write the code? Would be very thankful.

**Comment by asifehmad** [comment]
> > Try printing out the variable `data_paths`. Most probably the directory specified is incorrect.
> 
> Sir, didn't get it. Please, need your more help. Could you please write the code? Would be very thankful.

I tried: 
`print(data_paths)`
The answer: 
`[ ]`

**Comment by IAmSuyogJadhav** [comment]
Since printing `data_paths` outputs an empty list, that means either the specified path is incorrect OR there are no files in the specified path.

**Comment by asifehmad** [comment]
> Since printing `data_paths` outputs an empty list, that means either the specified path is incorrect OR there are no files in the specified path.

Thank You, sir, for the response! I will check it.
