### ISSUE TITLE
Data_loading

### ISSUE THREAD

**Issue by Qingyuncookie** [IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization#17]
The code is easy to read, you are really great! And I want to ask a question about the data loading, is all the data ready before training, I mean, do we need to load all the data into memory? Due to my pc have 48G memory but it doesn't contain all the data after pre-processing before training.

**Comment by IAmSuyogJadhav** [comment]
You can use Keras DataLoaders to load only 1 batch in the memory at a time. Pre-processing takes a lot of time if you are using N4 bias correction. Just have all your data preprocessed and save it to the disk. Later in use dataloaders to load the data in batches.
