### ISSUE TITLE
About Input size

### ISSUE THREAD

**Issue by Crispy13** [IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization#21]
Hello. I'm a noob in this part and try to this code on our dataset.
According to the article of nvdlmed, the input size is 4 x 160 x 192 x 128.

But the code is:
![image](https://user-images.githubusercontent.com/47196430/67912018-df9c3500-fbcb-11e9-9a24-3661b75dfb33.png)

Also after load nii a image using the read_img function the loaded numpy array's shape is (155, 240, 240).

I can understand how can 240 x 240 -> 192 x 128 converting happen(maybe crop), but can't understand how does the slice number increase(155 -> 160).

They are very confusing to me. Am i missing something about input size?

**Comment by IAmSuyogJadhav** [comment]
If you see the notebook, you will observe I used `scipy.ndimage.zoom` to resize the 3D image to our desired shape. When decreasing the size along a dimension (e. g., 240 -> 128), resizing is used (not cropping). For increasing the size along a dimension (e.g. 155 -> 160), interpolation is used. This is done internally by `scipy.ndimage.zoom`.

The reason I used an input size of 4*80*96*64 is just to reduce the amount of memory needed. The GPU offered by Google collaboratory (Tesla T4/K80) doesn't have enough. You can use whatever size that fits in your GPU, as long as you follow the input shape rules given in `README`

**Comment by Crispy13** [comment]
Thank you for reply!
I understand it now.

**Comment by Crispy13** [comment]
In 2. Related Work, 

> Compared to the related works, we use the largest crop size of 160x192x128
but compromise the batch size to be 1 to be able to fit network into the GPU
memory limits.

In  4. Results,

> During training we used a random crop of size 160x192x128,
which ensures that most image content remains within the crop area.

So it doesn't matter if i crop the images instead of resizing?

**Comment by IAmSuyogJadhav** [comment]
You can go for any of the approaches. Resizing is simpler as it only requires you to resize back the output to the original size. Cropping will retain the maximum amount of information, but then you will need to align the crops of a particular example correctly to reconstruct the segmentation.
