### ISSUE TITLE
for code section: Parameters for the progress bar, i am getting this error?

### ISSUE THREAD

**Issue by sneh-debug** [IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization#23]
---------------------------------------------------------------------------

ZeroDivisionError                         Traceback (most recent call last)

<ipython-input-18-5506a87447e1> in <module>()
      3 # Parameters for the progress bar
      4 total = len(data_paths[:4])
----> 5 step = 25 / total
      6 
      7 for i, imgs in enumerate(data_paths[:4]):

ZeroDivisionError: division by zero

**Comment by sneh-debug** [comment]
input_shape = (4, 80, 96, 64)
output_channels = 3
data = np.empty((len(data_paths[:4]),) + input_shape, dtype=np.float32)
labels = np.empty((len(data_paths[:4]), output_channels) + input_shape[1:], dtype=np.uint8)
print(data.shape)

I got this output:
(0, 4, 80, 96, 64)

**Comment by cue1997** [comment]
i met the same error...

**Comment by ytliang97** [comment]
Have you check that `glob.glob()` really load your data in the variable `data_path?`

**Comment by sneh-debug** [comment]
yes ,it fixed the error
