### ISSUE TITLE
nan loss for down-sized model

### ISSUE THREAD

**Issue by mpslxz** [IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization#3]
I get loss=nan when I try to run a down-sized version of your model on single channel data with batch size=1 and input size=(1, 128,128,128)
Any suggestions?

**Comment by IAmSuyogJadhav** [comment]
Oh, I sincerely do not have much idea about the training part yet. I can
help you better once I have trained it once, myself. Till then, you can try
clipping the outputs (by directly editing the model.py) or other methods.
If you get something that works, please let me know. I will include it in
the code itself, to help other users.

**Comment by IAmSuyogJadhav** [comment]
Hello again, @mpslxz !
I tried training the model myself and fixed an issue related to downsized models in 4c9d222ecdd1938c7a099ff92c0fce0878fbeec6. Can you please try the latest script and see if it solves your issue?

**Comment by mpslxz** [comment]
@IAmSuyogJadhav Thanks, but I manually was changing the dimensions in the dense. Also, my input is single channel instead of 4. So I change the output of VAE. Last, my labels are also single channel (instead of 3).
I still get nan loss when training it.

**Comment by IAmSuyogJadhav** [comment]
That you can achieve by directly editing the source code and changing the last convolutional layer. Thanks for pointing out it though, I will implement it directly in the code to accommodate various no. of channels in the output.
By the way, I am still trying to figure the NaN loss problem since yesterday. If you happen to find a fix, please communicate it back here so that everyone benefits from it. I will be working on it from my side too.

**Comment by mpslxz** [comment]
Yeah. I am working on it too.

**Comment by IAmSuyogJadhav** [comment]
Hello again, @mpslxz .
The problem was in the KL Divergence Loss Equation. I have applied a fix for it and it is now giving non-nan loss values. Check back in around 2-3 mins for the changed code.
I have also added an argument `output_channels` sos that the output can have any no. of channels as per the requirement.

**Comment by mpslxz** [comment]
@IAmSuyogJadhav Thanks for the fix. I see that you have clipped the values of mean to be between epsilon and 1. Since your prior is a Gaussian with mean 0 and std 1, I think another option might be having a tanh activation on z_mean and z_sigma so that both of them cover the values in [-1,1] interval.
This is what had worked for me in the past.

**Comment by IAmSuyogJadhav** [comment]
Ohh, nice idea. That seems more intuitive and efficient for the model to learn. Hadn't thought of that. Will do that the first thing next morning. But don't you think it will also make the model suffer from varnishing gradients, given that the model is so deep?

**Comment by mpslxz** [comment]
That might be a problem. Although I think if you only change the two activations, it might be fine. Let's see what happens.

**Comment by IAmSuyogJadhav** [comment]
Will do that in a separate branch, then.

**Comment by IAmSuyogJadhav** [comment]
Implemented that in this one: 454953f94c2b333d0222ccc1e534fc32d71bbe53

**Comment by IAmSuyogJadhav** [comment]
But wait, there's a caveat here. We are actually wrong about this improving the performance. I just asked a researcher friend of mine, and he cleared it up for me.
The mean and variance being between -1 and 1 is only for the sampling trick. The learned distribution can have any mean or variance, on the other hand. With the tanh activation function, we are actually limiting our model to a smaller latent space.

**Comment by mpslxz** [comment]
The thing that you are talking about is the noise prior. When you minimize the KL divergence, it is between the distribution parameters and a know prior, in this case N(0, I). The reason that the KL has that closed form solution is because of the Gaussian prior (0, I).

**Comment by IAmSuyogJadhav** [comment]
So, we compare the obtained distribution with the gaussian distribution when minimizing the KL divergence? Sorry, but I am quite a beginner when it comes to stats.

**Comment by IAmSuyogJadhav** [comment]
Closing this for now due to inactivity, feel free to raise a new issue.

**Comment by doc78** [comment]
I'm trying the following fix, that seems to work fine:

loss_KL=(1 / n) * K.sum(K.exp(z_var) + K.square(z_mean) - 1. - z_var,
        axis=-1
    )

I think the reason is that z_var is already log when comes out of the sampling function.
Please tell me what do you think about this fix.

**Comment by IAmSuyogJadhav** [comment]
@doc78 , Thanks a ton for pointing that out. I was wrong about the KL loss formula. Turns out `z_var` is indeed already log when it comes out of the sampling function. I missed that while writing the code. I tried your fix and it is working correctly, as expected. Will commit your changes shortly.
