### ISSUE TITLE
Error during Fitting the model.

### ISSUE THREAD

**Issue by vijayannepu** [IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization#31]
I am trying this model on brats 2019 dataset. Everything was okay but during fitting the model it is giving the following error. Can someone help me..
Here is the error 

**ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[[[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
         ...**

**Comment by Crispy13** [comment]
Could i see the shape of x_train, y_train and part of your code including .fit() method?

**Comment by vijayannepu** [comment]
**This was the .fit() method:**
model.fit(data,labels,batch_size=1,epochs=1,verbose=1)
**Shapes:** 
labels.shape : (4, 3, 80, 96, 64)
data.shape : (4, 4, 80, 96, 64)

I was just trying first on 4 images .

**Comment by Crispy13** [comment]
Thank you for information.

More information is needed. It would be good if you share part of your code which is reproducible.

**Comment by vijayannepu** [comment]
Thank you for the quick response.

The code is same as in the code provided through google colab in this project which was available here : 

https://colab.research.google.com/github/IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization/blob/master/Example_on_BRATS2018.ipynb

I am using same code as there were no change in the image size from 2018 to 2019 brats dataset. Only the size of dataset was increased. Correct me if I am wrong.

**Comment by Crispy13** [comment]
Please edit
model.fit(data,labels,batch_size=1,epochs=1,verbose=1)
to
model.fit(data, [labels, data], batch_size=1,epochs=1,verbose=1)

The model outputs 2 arrays. (one for segementation label, the other for VAE branch output(i.e. input-self.) Model.py file was edited recently, so the example notebook is not correspond to the new model.py file.

I will make a request for this to the author of this repository.

**Comment by vijayannepu** [comment]
Thank you so much.
Can you please tell me how to check the output segmentation label for another sample, manually.

**Comment by Crispy13** [comment]
Do you want to see prediction results of your trained model on new samples?

**Comment by vijayannepu** [comment]
Yes.

**Comment by Crispy13** [comment]
You can use predict() method of model object and matplotlib.pyplot.imshow. 
Detail can be found at stackoverflow.com

**Comment by IAmSuyogJadhav** [comment]
This issue should be solved by #32. Thus, closing it for now. Please feel free to reopen this issue if it is still not solved for you!
