### ISSUE TITLE
help!!ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays?

### ISSUE THREAD

**Issue by 675492062** [IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization#34]
Traceback (most recent call last):
  File "Example_on_BRATS2018.py", line 109, in <module>
    model.fit(data, labels, batch_size=1, epochs=1)
  File "/home/xxx/anaconda3/envs/tf108/lib/python3.6/site-packages/keras/engine/training.py", line 1630, in fit
    batch_size=batch_size)
  File "/home/xxx/anaconda3/envs/tf108/lib/python3.6/site-packages/keras/engine/training.py", line 1480, in _standardize_user_data
    exception_prefix='target')
  File "/home/xxx/anaconda3/envs/tf108/lib/python3.6/site-packages/keras/engine/training.py", line 86, in _standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[[[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],

**Comment by vijayannepu** [comment]
Please edit
model.fit(data,labels,batch_size=1,epochs=1,verbose=1)
to
model.fit(data, [labels, data], batch_size=1,epochs=1,verbose=1)

The model outputs 2 array. (one for segementation label, the other for VAE branch output(i.e. input-self.) Model.py file was edited recently, so the example notebook is not correspond to the new model.py file.

**Comment by vijayannepu** [comment]
Once completed, tell me the dice coefficient of Ground truth segmentation labels, I am getting it as Zero

**Comment by 675492062** [comment]
OK,thank you very much! Once completed, I will tell you my experiment results.

**Comment by 675492062** [comment]
@vijayannepu I have trained for 50 epochs on brats2018. The final results as below
loss: 0.0402 - Dec_GT_Output_loss: -0.0011 - Dec_VAE_Output_loss: 0.0412 - Dec_GT_Output_dice_coefficient: 0.0011 - Dec_VAE_Output_dice_coefficient: 0.8081
But, it just took about two minutes for train 50 epochs on such a large amount of data set
My lab config: 8*P100

**Comment by vijayannepu** [comment]
My Results :

 loss: 0.0164 - Dec_GT_Output_loss: 0.0000e+00 - Dec_VAE_Output_loss: 0.0164 - Dec_GT_Output_dice_coefficient: 0.0000e+00 - Dec_VAE_Output_dice_coefficient: 0.9231 - val_loss: 0.0139 - val_Dec_GT_Output_loss: 0.0000e+00 - val_Dec_VAE_Output_loss: 0.0139 - val_Dec_GT_Output_dice_coefficient: 0.0000e+00 - val_Dec_VAE_Output_dice_coefficient: 0.9362

I am giving a split for validation also.But I don't understand why the ground  truth Dice Coefficient is leading to Zero. By the way, Are you doing it on Brats 2018 or Brats 2019?

**Comment by 675492062** [comment]
1)On Brats 2018
2)I did not have a split for validation,  How many epochs have you trained? too big? Maybe it's over fitting, i think.

**Comment by vijayannepu** [comment]
Iam working on 2019 dataset.
Iam just giving 10 epochs.

**Comment by 675492062** [comment]
In Example_on_BRATS2018.py modified from Example_on_BRATS2018.ipynb, 
data = np.empty((len(data_paths[:4]),) + input_shape, dtype=np.float32)
labels = np.empty((len(data_paths[:4]), output_channels) + input_shape[1:], dtype=np.uint8)

# Parameters for the progress bar
total = len(data_paths[:4])
step = 25 / total

for i, imgs in enumerate(data_paths[:4]):
.....
those codes means the data fed into the mode are only the images of first four folders(first four patients)???

**Comment by 675492062** [comment]
Dice Coefficient== Zero? Oh, that's a so terrible result!  Are 10 epochs too few?  I don't know how many epochs the author has trained. Or you have changed many codes. @IAmSuyogJadhav

**Comment by vijayannepu** [comment]
> In Example_on_BRATS2018.py modified from Example_on_BRATS2018.ipynb,
> data = np.empty((len(data_paths[:4]),) + input_shape, dtype=np.float32)
> labels = np.empty((len(data_paths[:4]), output_channels) + input_shape[1:], dtype=np.uint8)
> 
> # Parameters for the progress bar
> total = len(data_paths[:4])
> step = 25 / total
> 
> for i, imgs in enumerate(data_paths[:4]):
> .....
> those codes means the data fed into the mode are only the images of first four folders(first four patients)???

Yes That code loads only 4 samples! It was mentioned there in notebook. We have to change that 4 to the number of samples in our dataset.

**Comment by vijayannepu** [comment]
> Dice Coefficient== Zero? Oh, that's a so terrible result! Are 10 epochs too few? I don't know how many epochs the author has trained. Or you have changed many codes. @IAmSuyogJadhav

Yes It is 0. I haven't changed much code. Just changed the number of samples 4 to 335(As in Brats 2019). Also 10 epochs were not few. 
If you have observed there, **Dec_VAE_Output_dice_coefficient** is almost 92 to 93. So 10 epochs is a decent number. I have checked for the data in "labels" also. Its not empty.
