### ISSUE TITLE
could anyone please help regarding this error?

### ISSUE THREAD

**Issue by srinivasb72s1** [IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization#36]
I have executed the given example on google colab. I changed the working directory into the working directory.  using the following code:

import os
os.chdir("/content/drive/My Drive/Colab Notebooks/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization-master")
that working directory having the following files:
Brats_2018     model.py			     __pycache__  testing.ipynb
group_norm.py  NVDLMED_Implementation.ipynb  README.md

when extract the datadet from below code
import zipfile  # For faster extraction
dataset_path = "/Brats_2018/MICCAI_BraTS_2018_Data_Training.zip"  
zfile = zipfile.ZipFile(dataset_path)
zfile.extractall()

error here is
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-28-a84b3a793787> in <module>()
      1 import zipfile  # For faster extraction
      2 dataset_path = "/Brats_2018/MICCAI_BraTS_2018_Data_Training.zip"  
----> 3 zfile = zipfile.ZipFile(dataset_path)
      4 zfile.extractall()

/usr/lib/python3.6/zipfile.py in __init__(self, file, mode, compression, allowZip64)
   1111             while True:
   1112                 try:
-> 1113                     self.fp = io.open(file, filemode)
   1114                 except OSError:
   1115                     if filemode in modeDict:

FileNotFoundError: [Errno 2] No such file or directory: '/Brats_2018/MICCAI_BraTS_2018_Data_Training.zip'

how to give datapath?
please help me 
thanking you.

**Comment by jayurbain** [comment]
Make sure your files are located at your datapath:

!ls -l dataset_path
