### ISSUE TITLE
model.fit ValueError Upgrading to tensorflow 2 (tf.keras)

### ISSUE THREAD

**Issue by jayurbain** [IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization#39]
First, thanks for everyone's contributions to this project.

I'm trying to upgrade from tf 1.15 using keras to tensorflow 2, i.e., tf.keras...

On the call to model.fit(), I get a value error (shown below). 
#Train the model
import tensorflow as tf
model.fit(data, [labels, data], batch_size=1, epochs=1, verbose=1)

Input and target data:
data is dtype('float32')
label is dtype('uint8')

Ultimately, the code is failing on a numpy multiply operation:
TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type uint8 of argument 'x'.

I've tried changing the np label array to tf.float32, casting the labels to tf.float32. I've also tried simpler loss functions.

Any direction would be appreciated. Thanks, Jay. 

model.fit() output: 
Train on 4 samples
1/4 [======>.......................] - ETA: 3s
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py in _apply_op_helper(op_type_name, name, **keywords)
    469               as_ref=input_arg.is_ref,
--> 470               preferred_dtype=default_dtype)
    471         except TypeError as err:

~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, dtype_hint, ctx, accepted_result_types)
   1316           "Tensor conversion requested dtype %s for Tensor with dtype %s: %r" %
-> 1317           (dtype.name, value.dtype.name, value))
   1318     return value

ValueError: Tensor conversion requested dtype uint8 for Tensor with dtype float32: <tf.Tensor 'model/Dec_GT_Output/Sigmoid:0' shape=(1, 3, 80, 96, 64) dtype=float32>

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-16-9a09ffaf79aa> in <module>
      2 # .astype("float32").values
      3 
----> 4 model.fit(data, [labels, data], batch_size=1, epochs=1, verbose=1)

...

~/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py in _apply_op_helper(op_type_name, name, **keywords)
    504                 "%s type %s of argument '%s'." %
    505                 (prefix, dtypes.as_dtype(attrs[input_arg.type_attr]).name,
--> 506                  inferred_from[input_arg.type_attr]))
    507 
    508         types = [values.dtype]

TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type uint8 of argument 'x'.

**Comment by IAmSuyogJadhav** [comment]
This script is not compatible with TF2.0. Please check #40
