### ISSUE TITLE
getting error while running in google co-lab

### ISSUE THREAD

**Issue by harimohanrai** [IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization#44]
i am getting error while running 
model = build_model(input_shape=input_shape, output_channels=3)
"module 'tensorflow._api.v2.config' has no attribute 'experimental_list_devices'"

please help me out.

**Comment by IAmSuyogJadhav** [comment]
Please have a look at #40. This model was designed in TensorFlow 1.x API. It is not compatible with TensorFlow 2.x. Please install the package versions mentioned in #40 to make use of the model.
