### ISSUE TITLE
This is not really an issue but could You give me a tutorial on how to run it on BRATS dataset?

### ISSUE THREAD

**Issue by michalstepniewski** [IAmSuyogJadhav/3d-mri-brain-tumor-segmentation-using-autoencoder-regularization#9]
This is not really an issue but could You give me a tutorial on how to run it on BRATS dataset?

**Comment by IAmSuyogJadhav** [comment]
@michalstepniewski , I have been getting requests for the same for quite a while now. I will upload the example notebook shortly,  using BRATS2018 dataset. 

P.S.: Sorry for replying late, had a pile of unread emails since last few days. Just saw this.

**Comment by IAmSuyogJadhav** [comment]
@michalstepniewski , please have a look at [Example_on_BRATS2018.ipynb](../blob/master/Example_on_BRATS2018.ipynb)
